spring:
  profiles:
    group:
      default:
        - local
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    baseline-version: 0
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  web:
    resources:
      static-locations: file:./src/main/resources/static/
      cache:
        period: 0
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  mustache:
    servlet:
      cache: false
  freemarker:
    cache: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  servlet:
    encoding:
      force: 'true'
  address: 0.0.0.0
  port: 8080
logging:
  level:
    com:
      example:
        accountbook: DEBUG

